In [1]:
import torch

##Tensor Initialisation

In [2]:
# Create a 2d tensor ( like array ): 
#                   [ [1,2,5]
#                     [3,4,2] ]

tensor = torch.tensor([[1,2,3],[3,4,2]])

In [3]:
print(tensor)

tensor([[1, 2, 3],
        [3, 4, 2]])


In [4]:
#Setting the type of tensor and whether to work on CPU or GPU
tensor = torch.tensor([[1,2,3],[3,4,2]],dtype = torch.float64,device = "cuda")

In [5]:
#Another thing that is often followed is 
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
# And then instead of specifying device specifically for different systems , above function will automatically manage the device
tensor = torch.tensor([[1,2,3],[3,4,2]],dtype = torch.float64,device =device)

In [7]:
tensor

tensor([[1., 2., 3.],
        [3., 4., 2.]], device='cuda:0', dtype=torch.float64)

In [8]:
tensor.dtype

torch.float64

In [9]:
tensor.device

device(type='cuda', index=0)

In [10]:
tensor.shape

torch.Size([2, 3])

In [11]:
tensor.requires_grad

False

In [12]:
# We can set whether a tensor will be used for gradient descent 
tensor = torch.tensor([[1,2,3],[3,4,2]],dtype = torch.float64,device =device,requires_grad=True)

###Other Initialisation Methods:

In [30]:
# Unitialised random data
x = torch.empty(size = (4,3))
x

tensor([[2.8114e-11, 3.0873e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [4.9115e-14, 1.4708e-41, 0.0000e+00]])

In [31]:
x_zero = torch.zeros((4,3))
x_zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
#Initialize random numbers inside the matrix ranging from 0-1
x_rand = torch.rand((4,3))
x_rand

tensor([[0.8124, 0.0094, 0.9189],
        [0.5737, 0.8045, 0.9988],
        [0.7804, 0.7559, 0.5561],
        [0.9858, 0.2953, 0.0328]])

In [33]:
x_ones = torch.ones((4,3))
x_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
# Identity matrix
# Notice the change in function input instead of (n,m) we use n,m
x_I = torch.eye(3,4)
x_I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [35]:
# Tensor in a range 
x_range = torch.arange(start = 7,end = 10,step = 1)
x_range

tensor([7, 8, 9])

In [36]:
# Linear spaced Range tensor
x_lin = torch.linspace(start = 100,end = 114.2,steps = 11)
x_lin

tensor([100.0000, 101.4200, 102.8400, 104.2600, 105.6800, 107.1000, 108.5200,
        109.9400, 111.3600, 112.7800, 114.2000])

In [37]:
#Normally distributed tensor
x_normal = torch.empty((3,3)).normal_(mean = 0,std = 1)
x_normal

tensor([[ 0.2610,  0.8278,  0.1662],
        [-1.3363, -0.7768, -1.0985],
        [ 1.1248,  2.3058,  1.1572]])

In [39]:
#Uniform distributed tensor
x_uniform = torch.empty((3,3)).uniform_(0,1)
x_uniform

tensor([[0.2701, 0.0634, 0.8292],
        [0.8500, 0.4835, 0.2250],
        [0.2229, 0.7545, 0.6890]])

In [40]:
#Using diagonal matrix
x_diag = torch.diag(torch.ones(3))
x_diag

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

##Converting tensors' datatype

In [2]:
test_tensor = torch.arange(start = 0,end = 9,step= 1)

In [3]:
test_tensor = test_tensor.long()

In [5]:
test_tensor.dtype

torch.int64

In [6]:
test_tensor = test_tensor.short()

In [7]:
test_tensor.dtype

torch.int16

##Numpy array to tensor

In [9]:
import numpy as np
np_array = np.zeros((5,3))

In [10]:
tensor = torch.from_numpy(np_array)

In [11]:
np_array_back = tensor.numpy()